name: check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y elpa-macaulay2 macaulay2 elpa-org
      - name: Run MELPA checks
        uses: leotaku/elisp-check@master
        with:
          file: ob-macaulay2.el
      - name: Run tests
        run: make check
