name: check

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - name: Install M2.el
        run: apt-get -y install elpa-macaulay2
      - uses: leotaku/elisp-check@master
        with:
          file: ob-macaulay2.el
